modLoader="javafml"
loaderVersion="[37,)"
license="BSD (3 clause)"

[[mods]]
modId="woodworking"
version="${file.jarVersion}"
displayName="Woodworking"
authors="gigaherz"
logoFile="logo.png"
description='''
A mod all about wood
'''
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/Woodworking/issues"
displayURL="https://github.com/gigaherz/Woodworking"
credits="Thanks for this example mod goes to Java"

[[dependencies.woodworking]]
   modId="forge"
   mandatory=true
   versionRange="[37.0.31,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.woodworking]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1,1.18)"
   ordering="NONE"
   side="BOTH"