modLoader="javafml"
loaderVersion="[32,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/Woodworking/issues"
displayURL="https://github.com/gigaherz/Woodworking"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"
license="BSD (3 clause)"

[[mods]]
modId="woodworking"
version="${file.jarVersion}"
displayName="Woodworking"
description='''
The toolkit for the rustic adventurer
'''

[[dependencies.woodworking]]
   modId="forge"
   mandatory=true
   versionRange="[32.0.108,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.woodworking]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.1,1.17)"
   ordering="NONE"
   side="BOTH"