@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package gigaherz.woodworking.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;